#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export TZ="UTC0"

/bin/mount -a
mount -t ramfs -o nr_inodes=1k,mode=770 /dev/ram /ramdisk
cp -ar /ramdisk_copy/* /ramdisk
/bin/mount -t ramfs /dev/ram /dev
[ -e /etc/device_table.txt ] && /sbin/makedevs -d /etc/device_table.txt /
/bin/mount -t devpts /dev/pts

exec /sbin/init 1>/dev/console 2>/dev/console
