#!/bin/sh

# Copyright (C) 2006 OpenWrt.org

# echo hotplug usb - action ${ACTION} prod ${PRODUCT} type ${TYPE} intf ${INTERFACE} dev ${DEVICE} devFs ${DEVFS} > /dev/console
# echo hotplug usb @${ACTION} @${SUBSYSTEM} @${PHYSDEVPATH} @${DEVPATH} @${MODALIAS} @${MAJOR} @${MINOR} @${DEVICENAME} > /dev/console

case "$ACTION" in
	add)
		if [ "${DEVICENAME:0:2}" == "lp" ] ; then
			cupsd.sh add $DEVICENAME
		fi
		;;
	remove)
		if [ "${DEVICENAME:0:2}" == "lp" ] ; then
			cupsd.sh del $DEVICENAME
		fi
		;;
esac	
