#!/bin/sh
# Copyright (C) 2006 OpenWrt.org 

START=99
start() {
	if ! [ -f /tmp/mDNS_lease.cfg ] ; then
		echo "!" > /tmp/mDNS_lease.cfg
	fi
	
	/usr/bin/mDNSClientPosix > /dev/console &		
}


case "$1" in
	"boot")		start	;;
	"start")	start	;;
#	"stop")		stop	;;
	*)
				echo $0 'boot  - setup and start USB function'
				echo $0 'start - start USB function'
#				echo $0 'stop  - stop USB function'
				;;
esac
