# Generated automatically from Makefile.in by configure.
#

include ../Rules.make
CFLAGS+=-I../include/ulogd

#  Normally You should not need to change anything below

all: conffile.o

distrib:

conffile.o: conffile.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f conffile.o

distclean:
	rm -f Makefile

install: all
