#!/bin/sh

WAN=`wandataif.sh`

enable=`ccfg_cli get enable@ddns`
svcidx=`ccfg_cli get select@ddns`
service=`ccfg_cli get service${svcidx}@ddns`
username=`ccfg_cli get username${svcidx}@ddns`
password=`ccfg_cli get password${svcidx}@ddns`
hostname=`ccfg_cli get hostname${svcidx}@ddns`

if [ "$enable" != 1 ] ||  [ -z "$WAN" ] || [ -z "$svcidx" ] || [ -z "$service" ] || [ -z "$username" ] || [ -z "$password" ] || [ -z "$hostname" ] ; then
	exit 0
fi

/usr/sbin/ez-ipupdate -S ${service} -u "${username}:${password}" -h "${hostname}" -i ${WAN} -d > /dev/null 2>&1 
