#!/bin/sh

#For SSL Certificate

ts=`date '+%H%M%S'`                                                            
cp -f /ramdisk/flash/rc.conf /tmp/rc.conf.$ts
cd /tmp

if [ -f /flash/Cert.pem ]; then
if [ "`grep "BEGIN CERTIFICATE" /flash/Cert.pem`" ]; then 
echo "@@@@@CERTSTART@@@@@" >> /tmp/rc.conf.$ts
cat /flash/Cert.pem >> /tmp/rc.conf.$ts
fi
fi

/bin/gzip -f rc.conf.$ts
if [ "$1" = "factoryconfig" ]; then
/usr/sbin/upgrade rc.conf.$ts.gz factoryconfig 0 0
else
/usr/sbin/upgrade rc.conf.$ts.gz sysconfig 0 0
fi
/bin/rm -f rc.conf.$ts.gz
cd - >/dev/null
