
ifeq ($(CONFIG_ETH_DRV_TEMPLATE),y)
obj-y += eth_drv_template.o
obj-y += eth_drv_template2.o
endif

#obj-$(CONFIG_ETH_DRV_TEMPLATE) := eth_drv_template.o 
#obj-$(CONFIG_ETH_DRV_TEMPLATE) := eth_drv_template2.o