
                         /*__NR_Linux 4000    */
"syscall",               /*(__NR_Linux + 0)   */
"exit",                  /*(__NR_Linux + 1)   */
"fork",                  /*(__NR_Linux + 2)   */
"read",                  /*(__NR_Linux + 3)   */
"write",                 /*(__NR_Linux + 4)   */
"open",                  /*(__NR_Linux + 5)   */
"close",                 /*(__NR_Linux + 6)   */
"waitpid",               /*(__NR_Linux + 7)   */
"creat",                 /*(__NR_Linux + 8)   */
"link",                  /*(__NR_Linux + 9)   */
"unlink",                /*(__NR_Linux + 10)  */
"execve",                /*(__NR_Linux + 11)  */
"chdir",                 /*(__NR_Linux + 12)  */
"time",                  /*(__NR_Linux + 13)  */
"mknod",                 /*(__NR_Linux + 14)  */
"chmod",                 /*(__NR_Linux + 15)  */
"lchown",                /*(__NR_Linux + 16)  */
"break",                 /*(__NR_Linux + 17)  */
"unused18",              /*(__NR_Linux + 18)  */
"lseek",                 /*(__NR_Linux + 19)  */
"getpid",                /*(__NR_Linux + 20)  */
"mount",                 /*(__NR_Linux + 21)  */
"umount",                /*(__NR_Linux + 22)  */
"setuid",                /*(__NR_Linux + 23)  */
"getuid",                /*(__NR_Linux + 24)  */
"stime",                 /*(__NR_Linux + 25)  */
"ptrace",                /*(__NR_Linux + 26)  */
"alarm",                 /*(__NR_Linux + 27)  */
"unused28",              /*(__NR_Linux + 28)  */
"pause",                 /*(__NR_Linux + 29)  */
"utime",                 /*(__NR_Linux + 30)  */
"stty",                  /*(__NR_Linux + 31)  */
"gtty",                  /*(__NR_Linux + 32)  */
"access",                /*(__NR_Linux + 33)  */
"nice",                  /*(__NR_Linux + 34)  */
"ftime",                 /*(__NR_Linux + 35)  */
"sync",                  /*(__NR_Linux + 36)  */
"kill",                  /*(__NR_Linux + 37)  */
"rename",                /*(__NR_Linux + 38)  */
"mkdir",                 /*(__NR_Linux + 39)  */
"rmdir",                 /*(__NR_Linux + 40)  */
"dup",                   /*(__NR_Linux + 41)  */
"pipe",                  /*(__NR_Linux + 42)  */
"times",                 /*(__NR_Linux + 43)  */
"prof",                  /*(__NR_Linux + 44)  */
"brk",                   /*(__NR_Linux + 45)  */
"setgid",                /*(__NR_Linux + 46)  */
"getgid",                /*(__NR_Linux + 47)  */
"signal",                /*(__NR_Linux + 48)  */
"geteuid",               /*(__NR_Linux + 49)  */
"getegid",               /*(__NR_Linux + 50)  */
"acct",                  /*(__NR_Linux + 51)  */
"umount2",               /*(__NR_Linux + 52)  */
"lock",                  /*(__NR_Linux + 53)  */
"ioctl",                 /*(__NR_Linux + 54)  */
"fcntl",                 /*(__NR_Linux + 55)  */
"mpx",                   /*(__NR_Linux + 56)  */
"setpgid",               /*(__NR_Linux + 57)  */
"ulimit",                /*(__NR_Linux + 58)  */
"unused59",              /*(__NR_Linux + 59)  */
"umask",                 /*(__NR_Linux + 60)  */
"chroot",                /*(__NR_Linux + 61)  */
"ustat",                 /*(__NR_Linux + 62)  */
"dup2",                  /*(__NR_Linux + 63)  */
"getppid",               /*(__NR_Linux + 64)  */
"getpgrp",               /*(__NR_Linux + 65)  */
"setsid",                /*(__NR_Linux + 66)  */
"sigaction",             /*(__NR_Linux + 67)  */
"sgetmask",              /*(__NR_Linux + 68)  */
"ssetmask",              /*(__NR_Linux + 69)  */
"setreuid",              /*(__NR_Linux + 70)  */
"setregid",              /*(__NR_Linux + 71)  */
"sigsuspend",            /*(__NR_Linux + 72)  */
"sigpending",            /*(__NR_Linux + 73)  */
"sethostname",           /*(__NR_Linux + 74)  */
"setrlimit",             /*(__NR_Linux + 75)  */
"getrlimit",             /*(__NR_Linux + 76)  */
"getrusage",             /*(__NR_Linux + 77)  */
"gettimeofday",          /*(__NR_Linux + 78)  */
"settimeofday",          /*(__NR_Linux + 79)  */
"getgroups",             /*(__NR_Linux + 80)  */
"setgroups",             /*(__NR_Linux + 81)  */
"reserved82",            /*(__NR_Linux + 82)  */
"symlink",               /*(__NR_Linux + 83)  */
"unused84",              /*(__NR_Linux + 84)  */
"readlink",              /*(__NR_Linux + 85)  */
"uselib",                /*(__NR_Linux + 86)  */
"swapon",                /*(__NR_Linux + 87)  */
"reboot",                /*(__NR_Linux + 88)  */
"readdir",               /*(__NR_Linux + 89)  */
"mmap",                  /*(__NR_Linux + 90)  */
"munmap",                /*(__NR_Linux + 91)  */
"truncate",              /*(__NR_Linux + 92)  */
"ftruncate",             /*(__NR_Linux + 93)  */
"fchmod",                /*(__NR_Linux + 94)  */
"fchown",                /*(__NR_Linux + 95)  */
"getpriority",           /*(__NR_Linux + 96)  */
"setpriority",           /*(__NR_Linux + 97)  */
"profil",                /*(__NR_Linux + 98)  */
"statfs",                /*(__NR_Linux + 99)  */
"fstatfs",               /*(__NR_Linux + 100) */
"ioperm",                /*(__NR_Linux + 101) */
"socketcall",            /*(__NR_Linux + 102) */
"syslog",                /*(__NR_Linux + 103) */
"setitimer",             /*(__NR_Linux + 104) */
"getitimer",             /*(__NR_Linux + 105) */
"stat",                  /*(__NR_Linux + 106) */
"lstat",                 /*(__NR_Linux + 107) */
"fstat",                 /*(__NR_Linux + 108) */
"unused109",             /*(__NR_Linux + 109) */
"iopl",                  /*(__NR_Linux + 110) */
"vhangup",               /*(__NR_Linux + 111) */
"idle",                  /*(__NR_Linux + 112) */
"vm86",                  /*(__NR_Linux + 113) */
"wait4",                 /*(__NR_Linux + 114) */
"swapoff",               /*(__NR_Linux + 115) */
"sysinfo",               /*(__NR_Linux + 116) */
"ipc",                   /*(__NR_Linux + 117) */
"fsync",                 /*(__NR_Linux + 118) */
"sigreturn",             /*(__NR_Linux + 119) */
"clone",                 /*(__NR_Linux + 120) */
"setdomainname",         /*(__NR_Linux + 121) */
"uname",                 /*(__NR_Linux + 122) */
"modify_ldt",            /*(__NR_Linux + 123) */
"adjtimex",              /*(__NR_Linux + 124) */
"mprotect",              /*(__NR_Linux + 125) */
"sigprocmask",           /*(__NR_Linux + 126) */
"create_module",         /*(__NR_Linux + 127) */
"init_module",           /*(__NR_Linux + 128) */
"delete_module",         /*(__NR_Linux + 129) */
"get_kernel_syms",       /*(__NR_Linux + 130) */
"quotactl",              /*(__NR_Linux + 131) */
"getpgid",               /*(__NR_Linux + 132) */
"fchdir",                /*(__NR_Linux + 133) */
"bdflush",               /*(__NR_Linux + 134) */
"sysfs",                 /*(__NR_Linux + 135) */
"personality",           /*(__NR_Linux + 136) */
"afs_syscall",           /*(__NR_Linux + 137) */
"setfsuid",              /*(__NR_Linux + 138) */
"setfsgid",              /*(__NR_Linux + 139) */
"_llseek",               /*(__NR_Linux + 140) */
"getdents",              /*(__NR_Linux + 141) */
"_newselect",            /*(__NR_Linux + 142) */
"flock",                 /*(__NR_Linux + 143) */
"msync",                 /*(__NR_Linux + 144) */
"readv",                 /*(__NR_Linux + 145) */
"writev",                /*(__NR_Linux + 146) */
"cacheflush",            /*(__NR_Linux + 147) */
"cachectl",              /*(__NR_Linux + 148) */
"sysmips",               /*(__NR_Linux + 149) */
"unused150",             /*(__NR_Linux + 150) */
"getsid",                /*(__NR_Linux + 151) */
"fdatasync",             /*(__NR_Linux + 152) */
"_sysctl",               /*(__NR_Linux + 153) */
"mlock",                 /*(__NR_Linux + 154) */
"munlock",               /*(__NR_Linux + 155) */
"mlockall",              /*(__NR_Linux + 156) */
"munlockall",            /*(__NR_Linux + 157) */
"sched_setparam",        /*(__NR_Linux + 158) */
"sched_getparam",        /*(__NR_Linux + 159) */
"sched_setscheduler",    /*(__NR_Linux + 160) */
"sched_getscheduler",    /*(__NR_Linux + 161) */
"sched_yield",           /*(__NR_Linux + 162) */
"sched_get_priority_max", /*(__NR_Linux + 163)*/
"sched_get_priority_min", /*(__NR_Linux + 164)*/
"sched_rr_get_interval", /*(__NR_Linux + 165) */
"nanosleep",             /*(__NR_Linux + 166) */
"mremap",                /*(__NR_Linux + 167) */
"accept",                /*(__NR_Linux + 168) */
"bind",                  /*(__NR_Linux + 169) */
"connect",               /*(__NR_Linux + 170) */
"getpeername",           /*(__NR_Linux + 171) */
"getsockname",           /*(__NR_Linux + 172) */
"getsockopt",            /*(__NR_Linux + 173) */
"listen",                /*(__NR_Linux + 174) */
"recv",                  /*(__NR_Linux + 175) */
"recvfrom",              /*(__NR_Linux + 176) */
"recvmsg",               /*(__NR_Linux + 177) */
"send",                  /*(__NR_Linux + 178) */
"sendmsg",               /*(__NR_Linux + 179) */
"sendto",                /*(__NR_Linux + 180) */
"setsockopt",            /*(__NR_Linux + 181) */
"shutdown",              /*(__NR_Linux + 182) */
"socket",                /*(__NR_Linux + 183) */
"socketpair",            /*(__NR_Linux + 184) */
"setresuid",             /*(__NR_Linux + 185) */
"getresuid",             /*(__NR_Linux + 186) */
"query_module",          /*(__NR_Linux + 187) */
"poll",                  /*(__NR_Linux + 188) */
"nfsservctl",            /*(__NR_Linux + 189) */
"setresgid",             /*(__NR_Linux + 190) */
"getresgid",             /*(__NR_Linux + 191) */
"prctl",                 /*(__NR_Linux + 192) */
"rt_sigreturn",          /*(__NR_Linux + 193) */
"rt_sigaction",          /*(__NR_Linux + 194) */
"rt_sigprocmask",        /*(__NR_Linux + 195) */
"rt_sigpending",         /*(__NR_Linux + 196) */
"rt_sigtimedwait",       /*(__NR_Linux + 197) */
"rt_sigqueueinfo",       /*(__NR_Linux + 198) */
"rt_sigsuspend",         /*(__NR_Linux + 199) */
"pread64",               /*(__NR_Linux + 200) */
"pwrite64",              /*(__NR_Linux + 201) */
"chown",                 /*(__NR_Linux + 202) */
"getcwd",                /*(__NR_Linux + 203) */
"capget",                /*(__NR_Linux + 204) */
"capset",                /*(__NR_Linux + 205) */
"sigaltstack",           /*(__NR_Linux + 206) */
"sendfile",              /*(__NR_Linux + 207) */
"getpmsg",               /*(__NR_Linux + 208) */
"putpmsg",               /*(__NR_Linux + 209) */
"mmap2",                 /*(__NR_Linux + 210) */
"truncate64",            /*(__NR_Linux + 211) */
"ftruncate64",           /*(__NR_Linux + 212) */
"stat64",                /*(__NR_Linux + 213) */
"lstat64",               /*(__NR_Linux + 214) */
"fstat64",               /*(__NR_Linux + 215) */
"pivot_root",            /*(__NR_Linux + 216) */
"mincore",               /*(__NR_Linux + 217) */
"madvise",               /*(__NR_Linux + 218) */
"getdents64",            /*(__NR_Linux + 219) */
"fcntl64",               /*(__NR_Linux + 220) */
"reserved221",           /*(__NR_Linux + 221) */
"gettid",                /*(__NR_Linux + 222) */
"readahead",             /*(__NR_Linux + 223) */
"setxattr",              /*(__NR_Linux + 224) */
"lsetxattr",             /*(__NR_Linux + 225) */
"fsetxattr",             /*(__NR_Linux + 226) */
"getxattr",              /*(__NR_Linux + 227) */
"lgetxattr",             /*(__NR_Linux + 228) */
"fgetxattr",             /*(__NR_Linux + 229) */
"listxattr",             /*(__NR_Linux + 230) */
"llistxattr",            /*(__NR_Linux + 231) */
"flistxattr",            /*(__NR_Linux + 232) */
"removexattr",           /*(__NR_Linux + 233) */
"lremovexattr",          /*(__NR_Linux + 234) */
"fremovexattr",          /*(__NR_Linux + 235) */
"tkill",                 /*(__NR_Linux + 236) */
"sendfile64",            /*(__NR_Linux + 237) */
"futex",                 /*(__NR_Linux + 238) */
"sched_setaffinity",     /*(__NR_Linux + 239) */
"sched_getaffinity",     /*(__NR_Linux + 240) */
"io_setup",              /*(__NR_Linux + 241) */
"io_destroy",            /*(__NR_Linux + 242) */
"io_getevents",          /*(__NR_Linux + 243) */
"io_submit",             /*(__NR_Linux + 244) */
"io_cancel",             /*(__NR_Linux + 245) */
"exit_group",            /*(__NR_Linux + 246) */
"lookup_dcookie",        /*(__NR_Linux + 247) */
"epoll_create",          /*(__NR_Linux + 248) */
"epoll_ctl",             /*(__NR_Linux + 249) */
"epoll_wait",            /*(__NR_Linux + 250) */
"remap_file_pages",      /*(__NR_Linux + 251) */
"set_tid_address",       /*(__NR_Linux + 252) */
"restart_syscall",       /*(__NR_Linux + 253) */
"fadvise64",             /*(__NR_Linux + 254) */
"statfs64",              /*(__NR_Linux + 255) */
"fstatfs64",             /*(__NR_Linux + 256) */
"timer_create",          /*(__NR_Linux + 257) */
"timer_settime",         /*(__NR_Linux + 258) */
"timer_gettime",         /*(__NR_Linux + 259) */
"timer_getoverrun",      /*(__NR_Linux + 260) */
"timer_delete",          /*(__NR_Linux + 261) */
"clock_settime",         /*(__NR_Linux + 262) */
"clock_gettime",         /*(__NR_Linux + 263) */
"clock_getres",          /*(__NR_Linux + 264) */
"clock_nanosleep",       /*(__NR_Linux + 265) */
"tgkill",                /*(__NR_Linux + 266) */
"utimes",                /*(__NR_Linux + 267) */
"mbind",                 /*(__NR_Linux + 268) */
"get_mempolicy",         /*(__NR_Linux + 269) */
"set_mempolicy",         /*(__NR_Linux + 270) */
"mq_open",               /*(__NR_Linux + 271) */
"mq_unlink",             /*(__NR_Linux + 272) */
"mq_timedsend",          /*(__NR_Linux + 273) */
"mq_timedreceive",       /*(__NR_Linux + 274) */
"mq_notify",             /*(__NR_Linux + 275) */
"mq_getsetattr",         /*(__NR_Linux + 276) */
"vserver",               /*(__NR_Linux + 277) */
"waitid",                /*(__NR_Linux + 278) */
"279",                   /*(sys_setaltroot (__NR_Linux + 279) */
"add_key",               /*(__NR_Linux + 280) */
"request_key",           /*(__NR_Linux + 281) */
"keyctl",                /*(__NR_Linux + 282) */
"set_thread_area",       /*(__NR_Linux + 283) */
"inotify_init",          /*(__NR_Linux + 284) */
"inotify_add_watch",     /*(__NR_Linux + 285) */
"inotify_rm_watch",      /*(__NR_Linux + 286) */
"migrate_pages",         /*(__NR_Linux + 287) */
"openat",                /*(__NR_Linux + 288) */
"mkdirat",               /*(__NR_Linux + 289) */
"mknodat",               /*(__NR_Linux + 290) */
"fchownat",              /*(__NR_Linux + 291) */
"futimesat",             /*(__NR_Linux + 292) */
"fstatat64",             /*(__NR_Linux + 293) */
"unlinkat",              /*(__NR_Linux + 294) */
"renameat",              /*(__NR_Linux + 295) */
"linkat",                /*(__NR_Linux + 296) */
"symlinkat",             /*(__NR_Linux + 297) */
"readlinkat",            /*(__NR_Linux + 298) */
"fchmodat",              /*(__NR_Linux + 299) */
"faccessat",             /*(__NR_Linux + 300) */
"pselect6",              /*(__NR_Linux + 301) */
"ppoll",                 /*(__NR_Linux + 302) */
"unshare",               /*(__NR_Linux + 303) */
"splice",                /*(__NR_Linux + 304) */
"sync_file_range",       /*(__NR_Linux + 305) */
"tee",                   /*(__NR_Linux + 306) */
"vmsplice",              /*(__NR_Linux + 307) */
"move_pages",            /*(__NR_Linux + 308) */
"set_robust_list",       /*(__NR_Linux + 309) */
"get_robust_list",       /*(__NR_Linux + 310) */
"kexec_load",            /*(__NR_Linux + 311) */
"getcpu",                /*(__NR_Linux + 312) */
"epoll_pwait",           /*(__NR_Linux + 313) */
"ioprio_set",            /*(__NR_Linux + 314) */
"ioprio_get",            /*(__NR_Linux + 315) */

                         /*"Linux_syscalls",    315*/
