#!/bin/sh /etc/rc.common

START=02

start() {

	if ! [ "$CONFIG_UBOOT_CONFIG_FIRMWARE_IN_ROOTFS" = "1" ]; then
		fw_mtd_hdr=`/bin/dd if=/dev/mtd1 bs=4 count=1 2>/dev/null`;
		if [ "$fw_mtd_hdr" = "sqlz" ] || [ "$fw_mtd_hdr" = "qshs" ] || [ "$fw_mtd_hdr" = "hsqs" ]; then
			echo "Mounting ADSL firmware.."
			/bin/mount /firmware
		else
			echo "ADSL firmware not found..!"
		fi
	fi

	[ `mount|grep -q nfs;echo $?` -eq  0 ] || /sbin/ifconfig eth0 0.0.0.0 up 2>/dev/null
	if [ -n "$CONFIG_TARGET_LTQCPE_PLATFORM_AR9_NONE" -a "$CONFIG_TARGET_LTQCPE_PLATFORM_AR9_NONE" = "1" -o -n "$CONFIG_TARGET_LTQCPE_PLATFORM_VR9_NONE" -a "$CONFIG_TARGET_LTQCPE_PLATFORM_VR9_NONE" = "1" ]; then
		[ `mount|grep -q nfs;echo $?` -eq  0 ] || /sbin/ifconfig eth1 0.0.0.0 up 2>/dev/null
	fi
#	br2684ctld
#	load_modules /etc/modules.d/*
	cd /tmp
	chmod 777 .

	# check for factory reset button
	if [ "$CONFIG_TARGET_LTQCPE_PLATFORM_AR9_VB" = "1" ]; then
		echo timer > /sys/class/leds/led_pwr/trigger
		if [ -e /dev/exin0 ] && [ "`cat /dev/exin0`" = "0" ]; then
			echo 100 > /sys/class/leds/led_pwr/delay_off
			echo 100 > /sys/class/leds/led_pwr/delay_on
			/usr/sbin/upgrade /etc/rc.conf.gz sysconfig 0 1 2>/dev/null
		fi
		echo 500 > /sys/class/leds/led_pwr/delay_off
		echo 500 > /sys/class/leds/led_pwr/delay_on
	fi

	#extract rc.conf
#	if [ "$CONFIG_UBOOT_CONFIG_BOOT_FROM_NAND" = "1" ]; then
#		if [ ! -f /etc/sysconfig/rc.conf.current.gz ]; then
#			cp -f /etc/rc.conf.gz /etc/sysconfig/rc.conf.current.gz; sync
#		fi
#		cp -f /etc/sysconfig/rc.conf.current.gz /ramdisk/flash/rc.conf.gz; sync
#		/bin/gunzip -f /ramdisk/flash/rc.conf.gz 2>/dev/null
#		if [ $? -ne 0 ]; then
#			cp -f /etc/rc.conf.gz /etc/sysconfig/rc.conf.current.gz; sync
#			cp -f /etc/sysconfig/rc.conf.current.gz /ramdisk/flash/rc.conf.gz; sync
#			/bin/gunzip -f /ramdisk/flash/rc.conf.gz 2>/dev/null
#		fi
#	else
		/usr/sbin/read_img sysconfig /ramdisk/flash/rc.conf.gz
		/bin/gunzip -f /ramdisk/flash/rc.conf.gz 2>/dev/null
		if [ $? -ne 0 ]; then
			/bin/rm -f /ramdisk/flash/rc.conf
			/usr/sbin/upgrade /etc/rc.conf.gz sysconfig 0 1 2>/dev/null
			/usr/sbin/read_img sysconfig /ramdisk/flash/rc.conf.gz
			/bin/gunzip -f /ramdisk/flash/rc.conf.gz
		fi
#	fi

	if [ "`grep "@@@@@CERTSTART@@@@@" /flash/rc.conf`" ]; then
		if [ "`grep "BEGIN CERTIFICATE" /flash/rc.conf`" ]; then
			sed -n -e '/@@@@@CERTSTART@@@@@/,$p' /flash/rc.conf > /tmp/lower.txt
			sed -n -e '1,/@@@@@CERTSTART@@@@@/p' /flash/rc.conf > /tmp/sed_upper.txt
			sed '/@@@@@CERTSTART@@@@@/d' /tmp/sed_upper.txt > /tmp/upper.txt
			sed '/@@@@@CERTSTART@@@@@/d' /tmp/lower.txt > /tmp/lower1.txt
			mv /tmp/lower1.txt /flash/Cert.pem
			mv /tmp/upper.txt /flash/rc.conf
			rm -rf /tmp/sed_upper.txt /tmp/lower.txt
		else
			sed '/@@@@@CERTSTART@@@@@/d' /flash/rc.conf > /tmp/rc.conf.tmp
			mv /tmp/rc.conf.tmp /flash/rc.conf
		fi
	fi

}
