#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

[ $# = 0 ] && { echo "  $0 <group>"; exit; }
[ "x$1" = "x-a" ] && {
	[ -e "/tmp/resolv.conf.auto" ] && rm /tmp/resolv.conf.auto
	config_cb() {
		[ interface != "$1" -o -z "$2" ] || eval "$0 $2"
	}
	. /etc/functions.sh
	config_load network
	exit
}

. /etc/functions.sh

if [ -z "$CONFIG_SECTION" ] ; then
	CONFIG_SECTION=$1
fi
	
include /lib/network
scan_interfaces

config_load network
config_get iftype "$1" type
config_get ifname "$1" device

for dev in $ifname; do
	setup_interface "$dev" "$1"
done
