#
# Copyright (C) 2009 Arcadyan Corporation
# All Rights Reserved.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=ifx-arc-patches
PKG_RELEASE:=1

PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)

include $(INCLUDE_DIR)/package.mk

define Package/$(PKG_NAME)
	SUBMENU:=Utilities
	SECTION:=utils
	CATEGORY:=Lantiq
	TITLE:=Arcadyan Patches of VR9 Configuration
endef

define Package/$(PKG_NAME)/description

endef

define Build/Prepare

endef

define Build/Compile
endef

define Package/$(PKG_NAME)/install

endef

define Build/InstallDev

endef

$(eval $(call BuildPackage,$(PKG_NAME)))
