/* Automatically generated by configure - do not modify! */
#define VERSION "1.1a"
#define PACKAGE "ushare"
#define PACKAGE_NAME "uShare"
#define SYSCONFDIR "/tmp"
#define LOCALEDIR "/usr/local/share/locale"
