#!/bin/sh

# Make a certificate/private key pair using a locally generated
# root certificate.
#
# Explicitly set nsCertType to server using the "server"
# extension in the openssl.cnf file.

cd /etc/openvpn/easy-rsa
source /tmp/vars

export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --server $*
