#!/bin/sh

# Initialize the $KEY_DIR directory.
# Note that this script does a
# rm -rf on $KEY_DIR so be careful!

RANDOM_NUMBER=`tr -cd 1000000000-9999990000 </dev/urandom | head -c 10`

cd /etc/openvpn/easy-rsa
source /tmp/vars

if [ "$KEY_DIR" ]; then
    rm -rf "$KEY_DIR"
    mkdir "$KEY_DIR" && \
	chmod go-rwx "$KEY_DIR" && \
	touch "$KEY_DIR/index.txt" && \
	echo ${RANDOM_NUMBER} >"$KEY_DIR/serial"
else
    echo 'Please source the vars script first (i.e. "source ./vars")'
    echo 'Make sure you have edited it to reflect your configuration.'
fi
