#ifndef __SWITCH_VENDOR_PROJECT__
#define __SWITCH_VENDOR_PROJECT__

/* Project */
#define	OS_TYPE_SUPERTASK								0x0100
#define OS_TYPE_LINUX										0x0200
#define OS_TYPE_MASK										0xFF00

#define PLATFORM_904DSL									0x0001
#define PLATFORM_TELEFORNICA						0x0002	
#define PLATFORM_MASK										0x00FF

#define PROJECT_PLATFORM								(OS_TYPE_LINUX|PLATFORM_904DSL)

//#if defined(SWITCH_REALTEK_RTL83XX_FAMILY)
#define SWITCH_REALTEK_RTL83XX_FAMILY


#endif // __SWITCH_VENDOR_PROJECT__
